ClientAppOracleTask/Entities/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientAppOracleTask.Entities
{
    public class Department : Entity
    {
        public string Name { get; set; }
        public string Info { get; set; }
        public List<Product> Products { get; set; }
    }
}

ClientAppOracleTask/Entities/Entity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientAppOracleTask.Entities
{
    public abstract class Entity
    {
        public int Id { get; set; }
    }
}

ClientAppOracleTask/Entities/Product.cs
namespace ClientAppOracleTask.Entities
{
    public class Product : Entity
    {
        public string ProductName { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public string Producer { get; set; }
        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }
    }
}

ClientAppOracleTask/Entities/Sale.cs
using System;

namespace ClientAppOracleTask.Entities
{
    public class Sale : Entity
    {
        public int CheckNo { get; set; }
        public int ProductId { get; set; }
        public DateTime DateSale { get; set; }
        public int Quantity { get; set; }
        public virtual Product Product { get; set; }
    }
}

ClientAppOracleTask/Models/AddSaleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientAppOracleTask.Models
{
    public class AddSaleViewModel
    {
        public int CheckNo { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
    }
}

ClientAppOracleTask/Models/ErrorViewModel.cs
using System;

namespace ClientAppOracleTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClientAppOracleTask/Controllers/DepartmentController.cs
using ClientAppOracleTask.Abstractions;
using ClientAppOracleTask.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ClientAppOracleTask.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IEntityService<Department> _entityService;

        public DepartmentController(IEntityService<Department> entityService)
        {
            _entityService = entityService;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var departments = await _entityService.GetInfoAsync();
            return View(departments);
        }
    }
}

ClientAppOracleTask/Controllers/HomeController.cs
using ClientAppOracleTask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ClientAppOracleTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var error = new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier };
            _logger.LogError(error.ToString());
            return View(error);
        }
    }
}

ClientAppOracleTask/Controllers/ProductController.cs
using ClientAppOracleTask.Abstractions;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ClientAppOracleTask.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var products = await _productService.GetInfoAsync();
            return View(products);
        }

        [HttpGet]
        public IActionResult ProductPrice()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ProductPriceAsync(string productName)
        {
            var price = await _productService.GetPrice(productName);
          
            ViewBag.ProductName = productName;
            ViewBag.Price = price.Value;

            return View();
        }
    }
}

ClientAppOracleTask/Controllers/SaleController.cs
using ClientAppOracleTask.Abstractions;
using ClientAppOracleTask.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace ClientAppOracleTask.Controllers
{
    public class SaleController : Controller
    {
        private readonly ISaleService _saleService;

        public SaleController(ISaleService saleService)
        {
            _saleService = saleService;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var sales = await _saleService.GetInfoAsync();
            return View(sales);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync(Sale model)
        {
            model.DateSale = DateTime.Now;
            if (ModelState.IsValid)
            {
                var addSaleResult = await _saleService.Add(model);
                if (addSaleResult.GetType().Equals(typeof(OkResult)))
                    return RedirectToAction(nameof(Index));
                else
                {
                    var result = addSaleResult as BadRequestObjectResult;
                    ModelState.AddModelError(string.Empty, result.Value.ToString());
                }   
            }
            return View(model);
        }
    }
}

ClientAppOracleTask/Views/Department/Index.cshtml
@model IEnumerable<ClientAppOracleTask.Entities.Department>
@{
    ViewBag.Title = "List of departments";
}

<table class="table">
    <tr><th>№</th><th>Department Name</th><th>Info</th></tr>
    @foreach (var department in Model)
    {
        <tr>
            <td>@department.Id</td>
            <td>@department.Name</td>
            <td>@department.Info</td>
        </tr>
    }
</table>

ClientAppOracleTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClientAppOracleTask/Views/Product/Index.cshtml
@model IEnumerable<ClientAppOracleTask.Entities.Product>
@{
    ViewBag.Title = "List of products";
}

<table class="table">
    <tr><th>№</th><th>Product Name</th><th>Price</th><th>Quantity</th><th>Producer</th><th>Producer Id</th></tr>
    @foreach (var product in Model)
    {
        <tr>
            <td>@product.Id</td>
            <td>@product.ProductName</td>
            <td>@product.Price</td>
            <td>@product.Quantity</td>
            <td>@product.Producer</td>
            <td>@product.DepartmentId</td>
        </tr>
    }
</table>

ClientAppOracleTask/Views/Product/ProductPrice.cshtml
@{
    ViewBag.Title = "Product price";
}

<h2>Enter a name of product</h2>
<form method="post" asp-controller="Product" asp-action="ProductPrice">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label class="control-label"></label>
        <input type="text" name="productName" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="View price" class="btn btn-outline-primary" />
    </div>
</form>

<h3>@ViewBag.ProductName</h3>
<h3>Price is: @ViewBag.Price</h3>

ClientAppOracleTask/Views/Sale/Add.cshtml
@model ClientAppOracleTask.Entities.Sale
@{ ViewBag.Title = "Add sale"; }

<h2>Add new sale</h2>
<form method="post" asp-controller="Sale" asp-action="Add">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="CheckNo" class="control-label"></label>
        <input type="number" asp-for="CheckNo" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ProductId" class="control-label"></label>
        <input type="number" asp-for="ProductId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Quantity" class="control-label"></label>
        <input type="number" asp-for="Quantity" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-outline-primary" />
    </div>
</form>

ClientAppOracleTask/Views/Sale/Index.cshtml
@model IEnumerable<ClientAppOracleTask.Entities.Sale>
@{
    ViewBag.Title = "List of sales";
}

<table class="table">
    <tr><th>№</th><th>CheckNo</th><th>ProductId</th><th>DateSale</th><th>Quantity</th></tr>
    @foreach (var sale in Model)
    {
        <tr>
            <td>@sale.Id</td>
            <td>@sale.CheckNo</td>
            <td>@sale.ProductId</td>
            <td>@sale.DateSale</td>
            <td>@sale.Quantity</td>
        </tr>
    }
</table>

ClientAppOracleTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientAppOracleTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClientAppOracleTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Sales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Add">Add Sale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductPrice">Product price</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ClientAppOracleTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>